site_name: Canonical's (unofficial) Observability docs
theme:
  name: material
markdown_extensions:
  # Fancy code blocks
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Icons and emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - autolinks
  - macros
